#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <dirent.h>
#include <sys/types.h>
#include <fcntl.h>
#include <termios.h>
#include <ctype.h>
#include <sys/stat.h>
#include <grp.h>
#include <time.h>
#include <sys/wait.h>
#include <pwd.h>
#include <signal.h>
#include "alias.h"
#include "auto.h"
#include "bg_jobs.h"
#include "cd.h"
#include "complete.h"
#include "discover.h"
#include "echo.h"
#include "execute.h"
#include "history.h"
#include "jobs.h"
#include "ls.h"
#include "nightswatch.h"
#include "pinfo.h"
#include "prompt.h"
#include "pwd.h"
#include "replay.h"


char *home_dir;
int homelen;
char history_path[1024];
int job;
char time_taken[1024];
int total_fore_time;
job_det *head;
alias *head_alias;
complete *head_complete;
int job_count;
int fore;
int back;
int last;
int history_count;
